<?php
/**
 * Title: Metrics rail
 * Slug: cinderwell-marketing/metrics-rail
 * Categories: cinderwell-marketing
 * Description: Three concise proof points in a tokenized Cinderwell Card Grid.
 * Keywords: metrics, stats, proof
 */
?>
<!-- wp:cinderwell/card-grid {"layout":"metrics","eyebrow":"Built for production","showEyebrow":true,"heading":"A small system with a wide reach.","cards":[{"id":"metric-one","label":"Blocks","title":"30+","description":"Purpose-built components sharing one predictable authoring model.","visualType":"none","showImage":false,"showLabel":true,"buttonUrl":"","buttonText":"","buttonVariant":"link","buttonSize":"sm"},{"id":"metric-two","label":"Breakpoints","title":"3","description":"Constrained desktop, tablet, and mobile decisions where they matter.","visualType":"none","showImage":false,"showLabel":true,"buttonUrl":"","buttonText":"","buttonVariant":"link","buttonSize":"sm"},{"id":"metric-three","label":"Foundation","title":"1","description":"A stable contract for themes, add-ons, editors, and developers.","visualType":"none","showImage":false,"showLabel":true,"buttonUrl":"","buttonText":"","buttonVariant":"link","buttonSize":"sm"}],"columns":"3","cardColor":"white","background":"light","width":"wide","align":"full"} -->
<div class="wp-block-cinderwell-card-grid alignfull cinderwell-card-grid cinderwell-card-grid--bg-light cinderwell-card-grid--cols-3 cinderwell-card-grid--cards-white"><div class="cinderwell-card-grid__inner" style="max-width:var(--cw-width-wide)"><span class="cinderwell-eyebrow">Built for production</span><h2 class="cinderwell-heading">A small system with a wide reach.</h2><div class="cinderwell-card-grid__grid"><div class="cinderwell-card-grid__card"><div class="cinderwell-card-grid__card-content"><span class="cinderwell-card-grid__card-label">Blocks</span><h3 class="cinderwell-card-grid__card-title">30+</h3><p class="cinderwell-card-grid__card-description">Purpose-built components sharing one predictable authoring model.</p></div></div><div class="cinderwell-card-grid__card"><div class="cinderwell-card-grid__card-content"><span class="cinderwell-card-grid__card-label">Breakpoints</span><h3 class="cinderwell-card-grid__card-title">3</h3><p class="cinderwell-card-grid__card-description">Constrained desktop, tablet, and mobile decisions where they matter.</p></div></div><div class="cinderwell-card-grid__card"><div class="cinderwell-card-grid__card-content"><span class="cinderwell-card-grid__card-label">Foundation</span><h3 class="cinderwell-card-grid__card-title">1</h3><p class="cinderwell-card-grid__card-description">A stable contract for themes, add-ons, editors, and developers.</p></div></div></div></div></div>
<!-- /wp:cinderwell/card-grid -->
